services:
    web:
        container_name: web
        build: ./apps/web
        ports:
            - ${WEB_PORT}:3000
        environment:
            - ORIGIN
            - JWT_SECRET
            - PUBLIC_IO_URL
    nest-socket:
        container_name: nest-socket
        build: ./apps/nest-socket
        ports:
            - ${NEST_PORT}:3000
        environment:
            - JWT_SECRET
